#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
import csv,collections,gzip
from pathlib import Path
p=Path(__file__).resolve().parent.parent
rows=list(csv.DictReader((p/'movement-counts.tsv').open(),delimiter='\t')); groups=collections.defaultdict(lambda:[set(),0,0,0,0,set()])
for r in rows:
 k=r['name'].split('.')[0];g=groups[k];g[0].add(r['encoding']);g[1]+=1;g[2]+=int(r['rows']);g[3]+=int(r['scalar_checked']);g[4]+=int(r['faults']);g[5].add((r['name'],r['encoding'],r['width']))
out=['# Class 1: data movement and widening','', '| Instruction | Encodings | Operand forms | Assembled immediate forms | Rows | Checked | Faults |','|---|---|---:|---:|---:|---:|---:|']
for k,g in groups.items():out.append(f'| {k} | {", ".join(sorted(g[0]))} | {len(g[5])} | {g[1]} | {g[2]} | {g[3]} | {g[4]} |')
expected=sum(int(r['rows']) for r in rows);faults=sum(int(r['faults']) for r in rows)
out += ['',f'Total: {len(rows)} separately assembled forms; {expected} predicted and observed rows. {expected-faults} complete scalar-result comparisons, {faults} fault-path scalar/state invariants. No instruction results are generated by the model.','', 'All PEXTR/PINSR, EXTRACTPS/INSERTPS and 128-bit insert/extract controls cover every immediate byte 0–255. For PEXTRW both SSE2 register-only and SSE4.1 register/memory opcodes are included, also their VEX counterparts. MOVQ and scalar MOVSS/MOVSD both load- and store-opcode register aliases are included.', '', 'Register forms use 9 fixed input patterns. Every memory form uses aligned and one-byte-misaligned pointers. Masked forms additionally use boundary-crossing protected-page lanes disabled/enabled, all-disabled protected-page addresses, all-enabled and alternating masks. Aligned-only instructions are deliberately run unaligned and their fault/context is recorded. Prefix/writes are observed using actual full YMM0 and YMM2 snapshots.', '', 'Reduction rule: 128-bit move chunks use two 64-bit pattern units (or the numbered-byte pattern), avoiding out-of-range scalar shifts. 9 deterministic source patterns; destination and extra source use different fixed nonzero patterns, rather than a full Cartesian product. Element patterns include zero, one, all ones, signed extrema, AA/55 and mixed edge lanes. Every legal requested SSE/VEX128/VEX256 operand form is retained. MOVLPD/MOVHPD and VBROADCASTI128 are included as useful adjacent forms.', '', 'Primary fields follow the task: X1 is the actual vector/GPR/memory destination before, and the first result is that destination after. Width is destination width. GPR values use 8 hex digits for 32-bit destinations and 16 for 64-bit destinations. X2/X3 are the actual sources (including GPR/memory inputs); absent sources are -. Full YMM/GPR/memory observations remain in named extras. UNKNOWN marks a memory value whose full span is inaccessible; MEM_BEFORE/MEM_AFTER show only the actual readable prefix with ACCESSIBLE_BYTES, never fabricated inaccessible bytes.', '', 'Scope/omissions: MMX, EVEX/AVX-512, privileged instructions, segment/address-size variants, redundant REX/prefix/register-number choices, and unrelated non-temporal moves are outside the requested SSE/AVX/AVX2 scope. VZEROUPPER/VZEROALL are supplied by class 10. Faulting operations have architectural invariants checked, not a fabricated successful value. The exact signal, trap and error code and actual fault-time YMM context are retained. No external or kernel memory is accessed.']
(p/'movement-COVERAGE.md').write_text('\n'.join(out)+'\n')
stat=collections.Counter()
with gzip.open(p/'out-movement.txt.gz','rt') as f:
 for line in f:
  if line.startswith('#'):continue
  name=line.split()[0];bad='FAULT=0 ' not in line
  enc='SSE' if '.SSE.' in name else 'VEX128' if '.VEX128.' in name else 'VEX256';stat[enc]+=1
  if 'guard_off' in name:stat['guard_off_fault' if bad else 'guard_off_success']+=1
  if 'alloff_guard' in name:stat['alloff_guard_fault' if bad else 'alloff_guard_success']+=1
rules=f'''# Class 1 observed rules

- Full-YMM checks: SSE rows {stat['SSE']}, VEX128 rows {stat['VEX128']}, VEX256 rows {stat['VEX256']}. Register-writing legacy forms preserve the initial YMM upper 128 bits. VEX128 register writes zero the upper 128 bits; store and GPR-destination instructions do not modify YMM0. VEXTRACT128 writes an XMM destination and zeros its YMM high half even though its source encoding uses L=1.
- Scalar legacy MOVSS/MOVSD register moves preserve untouched destination lanes; memory loads zero the rest of low XMM. VEX scalar register moves merge the explicit first source and zero the YMM high half.
- Every immediate byte is executed; extraction and insertion lane selectors ignore unused high bits. INSERTPS memory form ignores its source-lane selector, while its destination selector and zero-mask remain effective.
- Boundary guard-off cases: {stat['guard_off_success']} succeed, {stat['guard_off_fault']} fault. All-off protected-address cases: {stat['alloff_guard_success']} succeed, {stat['alloff_guard_fault']} fault. The faults in these two categories are MASKMOVDQU/VMASKMOVDQU on this host. VMASKMOVPS/PD and VPMASKMOVD/Q suppress protected-memory faults for disabled lanes and preserve disabled store bytes / zero disabled load lanes.
- All {faults} fault rows retain actual kernel signal-context snapshots, including YMM upper halves from XSAVE. Checked fault invariants: SIGSEGV, unchanged vector destination/mask/GPR, and accessible memory bytes equal either the original or the permitted scalar store result. MASKMOVDQU protected-address fault behavior is observed rather than assumed.
- {expected-faults} non-faulting rows match byte-for-byte scalar C models for destination, mask, GPR and accessible memory. {faults} fault rows match the stated invariants. Input/output rows and gzip bytes matched across two independent executions (gzip -n).
'''
(p/'movement-RULES.md').write_text(rules)
