#!/usr/bin/env python3
"""Emit native ELF/System V x86-64 assembly. MIT; see LICENSE."""
from pathlib import Path

out = ['''# Generated by generate_asm.py; MIT; see LICENSE.
.file "probes.S"
.text
.macro LOAD_FLAGS
    pushfq
    popq %r8
    movq %r8, %r9
    andq $-2262, %r9
    andq $2261, %rsi
    orq %rsi, %r9
    pushq %r9
    popfq
.endm
.macro RETURN_FLAGS
    andq $2261, %rax
    pushq %r8
    popfq
    ret
.endm
''']

for op in ('inc', 'dec', 'add', 'sub'):
    for width, reg, suffix in ((8,'dil','b'),(16,'di','w'),(32,'edi','l'),(64,'rdi','q')):
        name = f'probe_{op}{width}'
        instruction = f'{op}{suffix} ' + ('$1, ' if op in ('add','sub') else '') + f'%{reg}'
        out.append(f'''\n.globl {name}
.type {name}, @function
{name}:
    LOAD_FLAGS
    {instruction}
    pushfq
    popq %rax
    movq %rdi, (%rdx)
    RETURN_FLAGS
.size {name}, .-{name}
''')

for op, reg, low, whole in (('inc','ah','al','rax'),('dec','ch','cl','rcx')):
    name=f'probe_{op}_{reg}'
    # Seed unrelated register bits too. MOV/LEA are flag-neutral after LOAD_FLAGS.
    out.append(f'''\n.globl {name}
.type {name}, @function
{name}:
    movabsq $0x123456789abc00ef, %{whole}
    movb %dil, %{low}
    movb %{low}, %{reg}
    LOAD_FLAGS
    {op}b %{reg}
    pushfq
    popq %r10
    movzbl %{reg}, %ecx
    movq %rcx, (%rdx)
    movq %r10, %rax
    RETURN_FLAGS
.size {name}, .-{name}
''')

out.append('''
.globl probe_memory
.type probe_memory, @function
probe_memory:
    LOAD_FLAGS
    jmp *%rdx
.size probe_memory, .-probe_memory

.globl probe_load_flags
.type probe_load_flags, @function
probe_load_flags:
    movq %rdi, %rsi
    LOAD_FLAGS
    pushfq
    popq %rax
    RETURN_FLAGS
.size probe_load_flags, .-probe_load_flags

.type memory_return, @function
memory_return:
    RETURN_FLAGS
.size memory_return, .-memory_return
''')

variants = (
    ('cmp_m8_i8',256,[0x80,0x3f],1),
    ('test_m8_i8',256,[0xf6,0x07],1),
    ('cmp_m16_i8',256,[0x66,0x83,0x3f],1),
    ('cmp_m16_i16',65536,[0x66,0x81,0x3f],2),
    ('cmp_m32_i8',256,[0x83,0x3f],1),
)
for name, count, prefix, immbytes in variants:
    for imm in range(count):
        b=prefix+list(imm.to_bytes(immbytes,'little'))
        out.append(f'''.type {name}_{imm:04x}, @function
{name}_{imm:04x}:
    .byte {', '.join(hex(x) for x in b)}
    pushfq
    popq %rax
    jmp memory_return
.size {name}_{imm:04x}, .-{name}_{imm:04x}
''')

out.append('.section .rodata\n.p2align 3\n')
for name,count,_,_ in variants:
    out.append(f'.globl table_{name}\n.type table_{name}, @object\ntable_{name}:\n')
    out.extend(f'    .quad {name}_{imm:04x}\n' for imm in range(count))
    out.append(f'.size table_{name}, .-table_{name}\n')
out.append('.section .note.GNU-stack,"",@progbits\n')
Path(__file__).with_name('probes.S').write_text(''.join(out))
