/* SPDX-License-Identifier: MIT. Targeted values generated by native execution. */
#define EXTENDED_NO_MAIN
#include "extended.c"
#undef main
int main(void){
 ext80 pairs[][2]={
 {{UINT64_C(0x8000000000000001),0x3fff},{UINT64_C(0x8000000000000000),0x3fff}},
 {{UINT64_C(0x8000000000000000),0x43ff},{UINT64_C(0x8000000000000000),0x4000}},
 {{UINT64_C(0x8000000000000000),0x3bcc},{UINT64_C(0x8000000000000000),0x4000}},
 {{UINT64_C(0x8000000000000000),0x4002},{UINT64_C(0x8000000000000000),0x4000}}};
 puts("operation,pc,rounding,pair,a_80_hex,b_80_hex,x87_80_hex,sse_80_hex,a_narrow_hex,b_narrow_hex,fsw_before,fsw_after,a_narrow_fsw,b_narrow_fsw,mxcsr");
 for(int op=0;op<4;op++)for(int p=0;p<3;p++)for(int rc=0;rc<4;rc++)for(unsigned i=0;i<sizeof(pairs)/sizeof(*pairs);i++){int pc=pcs[p],fmt=pc==24?32:64;uint16_t cw=(pc==24?0x7f:pc==53?0x27f:0x37f)|(rc<<10),asw,bsw,before,after;uint32_t mx=0x1f80|(rc<<13);__asm__ volatile("fninit; fldcw %0"::"m"(cw));ext80 a=pairs[i][0],b=pairs[i][1],x;uint64_t na=narrow(a,fmt,&asw),nb=narrow(b,fmt,&bsw);result r;execute(op,fmt,na,nb,mx,&r);actual(op,a,b,&x,&before,&after);printf("%s,%d,%s,%u,%04x%016"PRIx64",%04x%016"PRIx64",%04x%016"PRIx64",%04x%016"PRIx64",%016"PRIx64",%016"PRIx64",%04x,%04x,%04x,%04x,%08x\n",opnames[op],pc,rcnames[rc],i,a.se,a.sig,b.se,b.sig,x.se,x.sig,r.s.se,r.s.sig,na,nb,before,after,asw,bsw,r.mx);}
 return 0;
}
