#!/usr/bin/env python3
"""Regenerate directed full-512-bit hardware witnesses on Linux x86-64.
The wider preceding emitter audit is NOT regenerated by this tool.
"""
import argparse,ctypes,hashlib,json,mmap,platform,struct,subprocess
from pathlib import Path
H=Path(__file__).resolve().parent

def cases():
    c=[]
    def add(name,asm,kind=0,mask=0x5): c.append(dict(name=name,asm=asm,kind=kind,k1=mask))
    for n in (0,1,7,8,15):
        for a,b,label in [('v','v','vex-vex'),('v','','vex-legacy'),('','v','legacy-vex'),('','','legacy-legacy')]:
            add(f'U01-pair-{label}-xmm{n}',f'{a}movups xmm{n},[rbx]\n{b}movups [rdi],xmm{n}',1)
        add(f'load128-vex-xmm{n}',f'vmovups xmm{n},[rbx]')
        add(f'load128-legacy-xmm{n}',f'movups xmm{n},[rbx]')
        add(f'movd-vex-r32-xmm{n}',f'vmovd xmm{n},eax')
        add(f'movd-legacy-r32-xmm{n}',f'movd xmm{n},eax')
        add(f'movq-vex-r64-xmm{n}',f'vmovq xmm{n},rax')
        add(f'movq-vex-mem-xmm{n}',f'vmovq xmm{n},[rbx]')
        add(f'movq-vex-xmm-xmm{n}',f'vmovq xmm{n},xmm1')
        add(f'mov-self-vex-xmm{n}',f'vmovups xmm{n},xmm{n}')
        add(f'mov-self-legacy-xmm{n}',f'movups xmm{n},xmm{n}')
        add(f'load256-ymm{n}',f'vmovups ymm{n},[rbx]')
        add(f'store256-ymm{n}',f'vmovups [rdi],ymm{n}')
    add('U01-evex128-pair','.byte 0x62,0xf1,0x7c,0x08,0x10,0x03\n.byte 0x62,0xf1,0x7c,0x08,0x11,0x07',1)
    add('movq-vex-F3-7E','.byte 0xc5,0xfa,0x7e,0xc1')
    add('movq-vex-66-D6','.byte 0xc5,0xf9,0xd6,0xc8')
    for n in (0,7,15,16,31):
        for mask in (0,1,5,15):
            add(f'M01-evex-merge-xmm{n}-k{mask}',f'vmovups xmm{n}{{k1}},[rbx]',2,mask)
            add(f'M01-evex-zero-xmm{n}-k{mask}',f'vmovups xmm{n}{{k1}}{{z}},[rbx]',2,mask)
    for op in ('andps','andnps','orps','xorps','pxor'):
        for s in ('xmm1','[rbx]'):
            add(f'logic-v{op}-{s}',f'v{op} xmm0,xmm0,{s}')
            add(f'logic-{op}-{s}',f'{op} xmm0,{s}')
    for op in ('punpcklbw','punpcklwd','punpckldq','punpcklqdq','punpckhbw','punpckhwd','punpckhdq','punpckhqdq','unpcklps','unpckhps'):
        for s in ('xmm1','[rbx]'):
            add(f'unpack-v{op}-{s}',f'v{op} xmm0,xmm0,{s}')
            add(f'unpack-{op}-{s}',f'{op} xmm0,{s}')
    for imm in range(256):
        add(f'insertps-vex-{imm}',f'vinsertps xmm0,xmm0,xmm1,{imm}')
        add(f'insertps-legacy-{imm}',f'insertps xmm0,xmm1,{imm}')
    for imm in range(4):
        for p in ('','v'):
            add(f'extractps-{p}-r-{imm}',f'{p}extractps eax,xmm1,{imm}')
            add(f'extractps-{p}-m-{imm}',f'{p}extractps [rdi],xmm1,{imm}')
    for op in ('addss','subss','mulss','divss','minss','maxss','addsd','subsd','mulsd','divsd','minsd','maxsd','addps','subps','mulps','divps','minps','maxps','addpd','subpd','mulpd','divpd','minpd','maxpd'):
        add(f'fp-v{op}',f'v{op} xmm0,xmm0,xmm1')
        add(f'fp-{op}',f'{op} xmm0,xmm1')
    for op in ('cvtss2sd','cvtsd2ss'):
        add(f'fp-v{op}',f'v{op} xmm0,xmm0,xmm1')
        add(f'fp-{op}',f'{op} xmm0,xmm1')
    for op in ('cvtsi2ss','cvtsi2sd'):
        for g in ('eax','rax'):
            add(f'fp-v{op}-{g}',f'v{op} xmm0,xmm0,{g}')
            add(f'fp-{op}-{g}',f'{op} xmm0,{g}')
    for op in ('cvtdq2pd','cvtps2pd','cvtpd2ps','cvtdq2ps','pshufd','pshuflw','pshufhw'):
        tail=',27' if op.startswith('pshuf') else ''
        add(f'fp-v{op}',f'v{op} xmm0,xmm1{tail}')
        add(f'fp-{op}',f'{op} xmm0,xmm1{tail}')
    for op in ('shufps','shufpd'):
        add(f'fp-v{op}',f'v{op} xmm0,xmm0,xmm1,1')
        add(f'fp-{op}',f'{op} xmm0,xmm1,1')
    return c

def seeded(seed):
    b=bytearray(2048)
    for n in range(32):
        for q in range(8):
            v=(0x1122334455667788 ^ (n*0x0101010101010101) ^ (q*0x9e3779b97f4a7c15) ^ seed)&((1<<64)-1)
            if q<2: v=(0x400000003f800000 if q==0 else 0x4080000040400000) ^ (n*257+seed)
            struct.pack_into('<Q',b,n*64+q*8,v)
    mem=bytearray((i*37+seed*11)&255 for i in range(256))
    for i in range(8): struct.pack_into('<I',mem,4*i,0x3f800000+i*0x00800000+seed)
    return bytes(b),bytes(mem)

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--out',type=Path,required=True);a=ap.parse_args()
    if platform.system()!='Linux' or platform.machine()!='x86_64':raise SystemExit('requires Linux x86-64 hardware')
    a.out.mkdir(parents=True,exist_ok=True);w=a.out/'build';w.mkdir(exist_ok=True)
    subprocess.run(['clang','-O2','-shared','-fPIC',str(H/'native_oracle.c'),str(H/'native_seed.S'),'-o',str(w/'oracle.so')],check=True)
    lib=ctypes.CDLL(str(w/'oracle.so'))
    if not lib.hb_upper_native_available():raise SystemExit('AVX512F/DQ/BW/VL or OS ZMM state not available')
    lib.hb_upper_native.argtypes=[ctypes.c_void_p]*4+[ctypes.c_uint64,ctypes.c_uint64]
    cs=cases();s=['.intel_syntax noprefix','.text']
    for i,c in enumerate(cs):s += [f'.global upper_{i}',f'upper_{i}:',c['asm'],'ret']
    (w/'forms.S').write_text('\n'.join(s)+'\n')
    subprocess.run(['clang','-c',str(w/'forms.S'),'-o',str(w/'forms.o')],check=True)
    subprocess.run(['objcopy','-O','binary','--only-section=.text',str(w/'forms.o'),str(w/'forms.bin')],check=True)
    dis=subprocess.check_output(['objdump','-d','-Mintel',str(w/'forms.o')],text=True);(a.out/'x86-disassembly.txt').write_text(dis)
    syms=subprocess.check_output(['nm','-n',str(w/'forms.o')],text=True)
    offs={int(l.split()[-1].split('_')[1]):int(l.split()[0],16) for l in syms.splitlines() if ' upper_' in l}
    code=(w/'forms.bin').read_bytes();mapping=mmap.mmap(-1,len(code),prot=mmap.PROT_READ|mmap.PROT_WRITE);mapping.write(code)
    addr=ctypes.addressof(ctypes.c_char.from_buffer(mapping));libc=ctypes.CDLL(None,use_errno=True)
    libc.mprotect.argtypes=[ctypes.c_void_p,ctypes.c_size_t,ctypes.c_int]
    if libc.mprotect(addr,len(code),mmap.PROT_READ|mmap.PROT_EXEC):raise OSError(ctypes.get_errno(),'mprotect')
    buf=a.out/'native.cases';raw=a.out/'native-measurements.jsonl';digest=hashlib.sha256();seeds=(1,0x1234,0x7744147);nexec=0
    with buf.open('wb') as f,raw.open('w') as records:
        f.write(b'HBUP0001'+struct.pack('<I',len(cs)*len(seeds)))
        for i,c in enumerate(cs):
            end=offs[i+1] if i+1 in offs else len(code);bc=code[offs[i]:end-1];c['bytes']=bc.hex()
            for seed in seeds:
                inp,mem=seeded(seed);ib=ctypes.create_string_buffer(inp);ob=ctypes.create_string_buffer(2048);mb=ctypes.create_string_buffer(mem)
                lib.hb_upper_native(ib,ob,mb,addr+offs[i],0x12345678fedcba98,c['k1'])
                out=ob.raw;om=mb.raw[:256];nexec+=1;digest.update(out+om)
                name=c['name'].encode();f.write(struct.pack('<HHIQQ',len(name),len(bc),c['kind'],seed,c['k1'])+name+bc+inp+mem+out+om)
                records.write(json.dumps(dict(name=c['name'],seed=hex(seed),bytes=bc.hex(),kind=c['kind'],mask=c['k1'],input_zmm=inp.hex(),input_mem=mem.hex(),hardware_zmm=out.hex(),hardware_mem=om.hex()),separators=(',',':'))+'\n')
    (a.out/'forms.json').write_text(json.dumps(cs,indent=2)+'\n')
    summary=dict(executor='native Linux x86-64 instructions, KVM; no ARM execution',cpu=subprocess.check_output(['lscpu'],text=True),forms=len(cs),seeds=list(map(hex,seeds)),hardware_executions=nexec,hardware_sha256=digest.hexdigest(),corpus_sha256=hashlib.sha256(buf.read_bytes()).hexdigest(),scope='directed full 32x512-bit vector snapshots and 256 memory bytes; no GPR/flags/exception comparison; not the previous 1683-case emitter corpus')
    (a.out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps({k:v for k,v in summary.items() if k!='cpu'},indent=2))
if __name__=='__main__':main()
