.text
.global case_0
case_0:
movb %bl, (%rdi)
.global case_1
case_1:
movb $-91, (%rdi)
.global case_2
case_2:
stosb
.global case_3
case_3:
rep stosb
.global case_4
case_4:
rep stosb
.global case_5
case_5:
rep stosb
.global case_6
case_6:
rep stosb
.global case_7
case_7:
movsb
.global case_8
case_8:
rep movsb
.global case_9
case_9:
rep movsb
.global case_10
case_10:
rep movsb
.global case_11
case_11:
rep movsb
.global case_12
case_12:
stosb
.global case_13
case_13:
rep stosb
.global case_14
case_14:
rep stosb
.global case_15
case_15:
rep stosb
.global case_16
case_16:
rep stosb
.global case_17
case_17:
movsb
.global case_18
case_18:
rep movsb
.global case_19
case_19:
rep movsb
.global case_20
case_20:
rep movsb
.global case_21
case_21:
rep movsb
.global case_22
case_22:
movw %bx, (%rdi)
.global case_23
case_23:
movw $-18779, (%rdi)
.global case_24
case_24:
stosw
.global case_25
case_25:
rep stosw
.global case_26
case_26:
rep stosw
.global case_27
case_27:
rep stosw
.global case_28
case_28:
rep stosw
.global case_29
case_29:
movsw
.global case_30
case_30:
rep movsw
.global case_31
case_31:
rep movsw
.global case_32
case_32:
rep movsw
.global case_33
case_33:
rep movsw
.global case_34
case_34:
stosw
.global case_35
case_35:
rep stosw
.global case_36
case_36:
rep stosw
.global case_37
case_37:
rep stosw
.global case_38
case_38:
rep stosw
.global case_39
case_39:
movsw
.global case_40
case_40:
rep movsw
.global case_41
case_41:
rep movsw
.global case_42
case_42:
rep movsw
.global case_43
case_43:
rep movsw
.global case_44
case_44:
movl %ebx, (%rdi)
.global case_45
case_45:
movl $-658000219, (%rdi)
.global case_46
case_46:
stosl
.global case_47
case_47:
rep stosl
.global case_48
case_48:
rep stosl
.global case_49
case_49:
rep stosl
.global case_50
case_50:
rep stosl
.global case_51
case_51:
movsl
.global case_52
case_52:
rep movsl
.global case_53
case_53:
rep movsl
.global case_54
case_54:
rep movsl
.global case_55
case_55:
rep movsl
.global case_56
case_56:
stosl
.global case_57
case_57:
rep stosl
.global case_58
case_58:
rep stosl
.global case_59
case_59:
rep stosl
.global case_60
case_60:
rep stosl
.global case_61
case_61:
movsl
.global case_62
case_62:
rep movsl
.global case_63
case_63:
rep movsl
.global case_64
case_64:
rep movsl
.global case_65
case_65:
rep movsl
.global case_66
case_66:
movq %rbx, (%rdi)
.global case_67
case_67:
movq $-658000219, (%rdi)
.global case_68
case_68:
stosq
.global case_69
case_69:
rep stosq
.global case_70
case_70:
rep stosq
.global case_71
case_71:
rep stosq
.global case_72
case_72:
rep stosq
.global case_73
case_73:
movsq
.global case_74
case_74:
rep movsq
.global case_75
case_75:
rep movsq
.global case_76
case_76:
rep movsq
.global case_77
case_77:
rep movsq
.global case_78
case_78:
stosq
.global case_79
case_79:
rep stosq
.global case_80
case_80:
rep stosq
.global case_81
case_81:
rep stosq
.global case_82
case_82:
rep stosq
.global case_83
case_83:
movsq
.global case_84
case_84:
rep movsq
.global case_85
case_85:
rep movsq
.global case_86
case_86:
rep movsq
.global case_87
case_87:
rep movsq
.global case_88
case_88:
movnti %ebx, (%rdi)
.global case_89
case_89:
movnti %rbx, (%rdi)
.global case_90
case_90:
pushw %bx
.global case_91
case_91:
pushw $-61
.global case_92
case_92:
pushw $-18779
.global case_93
case_93:
pushw (%rsi)
.global case_94
case_94:
pushq %rbx
.global case_95
case_95:
pushq $-61
.global case_96
case_96:
pushq $-658000219
.global case_97
case_97:
pushq (%rsi)
.global case_98
case_98:
call .+5
.global case_end
case_end:
